### ISSUE TITLE
Having the native string for each language would be nice

### ISSUE THREAD

**Issue by butterbrain** [atn832/language_picker#6]
Currently to pick a language you need to know the english for that language, as well as a language name for each, the native name would be a nice addition

**Comment by AdrienLemaire** [comment]
@atn832 what is blocking the merging of #7 ?

Another option would be to internationalize all strings, either with arb or simple dart objects, as done in [country_picker](https://github.com/Daniel-Ioannou/flutter_country_picker/tree/master/lib/src/res/strings) :)

**Comment by atn832** [comment]
@butterbrain @AdrienLemaire i had missed the email notification and didn't see @butterbrain 's PR until now. It looks good. Btw their PR wouldn't show the native language in the UI yet, would it? I'll take a closer look this week or weekend.

**Comment by atn832** [comment]
Thanks @butterbrain! I've just published your change to https://pub.dev/packages/language_picker/changelog#045.

**Comment by butterbrain** [comment]
Excellent, thank you for producing something so useful (O:
