### ISSUE TITLE
Flutter 3.22 : my_alert_dialog.dart:107:46: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.

### ISSUE THREAD

**Issue by tef-github** [atn832/language_picker#9]
Error ../.pub-cache/hosted/pub.dev/language_picker-0.4.3/lib/utils/my_alert_dialog.dart:107:46: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.

**Comment by sdattatri** [comment]
Many deprecated methods have been removed in 3.22. Check here.  https://docs.flutter.dev/release/breaking-changes/3-19-deprecations#texttheme. Kindly fix and release.

**Comment by m-hamza-tanbits** [comment]
@tef-github 
just replace your text headline6 to titleLarge. in my alert dialog class 
Line no 107 : style: Theme.of(context).textTheme.titleLarge!,

**Comment by atn832** [comment]
Two people generously provided a fix, which I just published https://pub.dev/packages/language_picker/changelog#0441. If you upgrade to 0.4.4, your project should compile.

**Comment by sdattatri** [comment]
Thank you!

Sanjay Dattatri,
